davydovanton/sidekiq-statistic

lib/sidekiq/history/statistic.rb, lib/sidekiq/history/statistic/runtime_statistic.rb, lib/sidekiq/history/views/history.erb, lib/sidekiq/history/views/history.js, lib/sidekiq/history/views/sidekiq-history.css, lib/sidekiq/history/views/worker.erb, lib/sidekiq/history/web_extension.rb
=> Add page with worker information table

lib/sidekiq/history.rb, lib/sidekiq/history/middleware.rb, lib/sidekiq/history/statistic/redis_statistic.rb, lib/sidekiq/history/statistic/runtime_statistic.rb, test/minitest_helper.rb, test/test_sidekiq/middleware_test.rb, test/test_sidekiq/redis_statistic_test.rb, test/test_sidekiq/runtime_statistic_test.rb, test/test_sidekiq/statistic_test.rb
=> Use native redis hash instead json serialization

lib/sidekiq/statistic/base.rb, lib/sidekiq/statistic/middleware.rb, lib/sidekiq/statistic/statistic/runtime.rb, test/test_sidekiq/base_statistic_test.rb
@mperham could you check this PR? It's simple realization for you comment https://github.com/davydovanton/sidekiq-statistic/pull/33#discussion_r34944402.
=> Use redis lists for save all job runtimes

lib/sidekiq/statistic/middleware.rb
1. Simplify code, remove unnecessary methods
2. Use a single finish time to ensure consistency of metrics
3. Minimize object allocation, e.g. don't allocate 'statistics' array
4. Pipeline redis commands for performance
=> Middleware refactoring

lib/sidekiq/statistic/locales/de.yml
=> Add German Localization

lib/sidekiq/statistic/log_parser.rb, lib/sidekiq/statistic/views/sidekiq-statistic.css, lib/sidekiq/statistic/views/statistic.js, lib/sidekiq/statistic/views/worker.erb, test/helpers/logfile.log, test/test_sidekiq/log_parser_test.rb
reference #40
@marshall-lee what do you think, this realisation is good for you?
=> Add button in log page for display only special job

lib/sidekiq/statistic/locales/it.yml
For #37. Thanks for this awesome project.
=> Italian localization

lib/sidekiq/statistic/middleware.rb, test/test_sidekiq/middleware_test.rb
=> Fix worker naming for AJ mailers

README.md
without this getting error with sinatra app
=> Session middleware err not rails app

lib/sidekiq/statistic/locales/de.yml, lib/sidekiq/statistic/locales/en.yml, lib/sidekiq/statistic/locales/it.yml, lib/sidekiq/statistic/locales/ru.yml, lib/sidekiq/statistic/middleware.rb, lib/sidekiq/statistic/statistic/workers.rb, lib/sidekiq/statistic/views/statistic.erb, test/minitest_helper.rb, test/test_sidekiq/base_statistic_test.rb, test/test_sidekiq/middleware_test.rb, test/test_sidekiq/web_api_extension_test.rb
=> Add queue to workers table in index page

lib/sidekiq/statistic/views/sidekiq-statistic.css, lib/sidekiq/statistic/views/statistic.erb, lib/sidekiq/statistic/views/statistic.js
=> Fix chart tooltip bug for many workers

lib/sidekiq/statistic/base.rb, lib/sidekiq/statistic/statistic/charts.rb, test/test_sidekiq/web_api_extension_test.rb
=> Sort worker names in GUI

lib/sidekiq/statistic/base.rb, lib/sidekiq/statistic/middleware.rb
=> Use strftime to ensure date string format

lib/sidekiq/statistic/views/statistic.js
=> Initialize charts only if page have charts id

sidekiq-statistic.gemspec
Tested with sidekiq 4.0.0.pre2.
=> Update gemspec to allow usage with sidekiq 4

lib/sidekiq/statistic/locales/uk.yml
File lib/sidekiq/statistic/locales/uk.yml
=> Added Ukrainian language 

lib/sidekiq/statistic/locales/ru.yml
Hi Anton,
this commit fixes typos in ru.yml
=> fixed typos

lib/sidekiq/statistic/version.rb, lib/sidekiq/statistic/web_extension.rb, sidekiq-statistic.gemspec
Fixes broken UI stuff. As far as I can tell the actual stats still work OK.
=> Fixes for Sidekiq 5

CHANGELOG.md, README.md, lib/sidekiq/statistic/web_api_extension.rb, test/test_sidekiq/middleware_test.rb, test/test_sidekiq/runtime_test.rb
Hopefully fixes the broken TravisCI build.
=> Fix tests, README and CHANGELOG

README.md
It didnt show the image. Now it does :D
=> Fix small error with the summary

README.md
Replace `Sidekiq::Statistic.configuration` to `Sidekiq::Statistic.configure` according to configure method in master branch
=> Update README.md (configuration manual)

lib/sidekiq/statistic/locales/pt-BR.yml
New locale file for brazilian portuguese pt-BR
=> New locale file for pt-BR

lib/sidekiq/statistic/locales/jp.yml
=> Add Japanese Localization

lib/sidekiq/statistic/locales/jp.yml
Better translation of LastJobStatus
=> Change translate of LastJobStatus

lib/sidekiq/statistic/locales/fr.yml
Tracking: https://github.com/davydovanton/sidekiq-statistic/issues/37
=> Add translations for French

lib/sidekiq/statistic/web_extension_helper.rb, test/test_sidekiq/web_extension_helper_test.rb, test/test_sidekiq/web_extension_test.rb
I wrote new test for ```web_extension_helper``` module, for ```calculate_date_range``` function.
For that module was the only function not covered by test case.
=> test for WebextensionHelper

test/test_sidekiq/statistic_test.rb
Improve test coverage
tests for `Sidekiq::Statistic::Worker` methods
=> Improve test coverage

lib/sidekiq/statistic/views/statistic.erb, lib/sidekiq/statistic/views/statistic.js
=> chart behavior with many workers

CHANGELOG.md
Related to: https://github.com/davydovanton/sidekiq-statistic/issues/143
=> Organize CHANGELOG to better reflect the new release

README.md
update image to reflect actual version of the gem
=> Update index screenshoot

lib/sidekiq/statistic/locales/de.yml, lib/sidekiq/statistic/locales/en.yml, lib/sidekiq/statistic/locales/fr.yml, lib/sidekiq/statistic/locales/it.yml, lib/sidekiq/statistic/locales/jp.yml, lib/sidekiq/statistic/locales/pt-br.yml, lib/sidekiq/statistic/locales/ru.yml, lib/sidekiq/statistic/locales/uk.yml, lib/sidekiq/statistic/views/realtime.erb, lib/sidekiq/statistic/views/realtime_statistic.js
I created this PR to create a possible solution to #131, but I think the position of button is not the better
=> Create a button to stop and start realtime charts

CHANGELOG.md, lib/sidekiq/statistic/locales/pt-br.yml
A fix at pt-br translation requested by issue https://github.com/davydovanton/sidekiq-statistic/issues/153
=> fix pt-br translation for start/stop

CHANGELOG.md, lib/sidekiq/statistic/views/realtime.erb, lib/sidekiq/statistic/views/realtime_statistic.js, lib/sidekiq/statistic/views/sidekiq-statistic.css
This PR is a refactoring on the realtime/statistic JS code, and was made for some reasons like:
- Reorganize the JS code to a better maintainability;
- Add ES6 syntax to the code, like suggested [here](https://github.com/davydovanton/sidekiq-statistic/pull/156#discussion_r447954184)
- Facilitate the development of new features like [this one](https://github.com/davydovanton/sidekiq-statistic/issues/155).
This PR don't change any behavior of the lib.
=> Refactor realtime statistic JS code

lib/sidekiq/statistic/locales/es.yml
=> Feature: add spanish locale file

CHANGELOG.md, lib/sidekiq/statistic/version.rb
Related to: https://github.com/davydovanton/sidekiq-statistic/issues/169
=> Create v1.5.1 in order to fix version.rb

lib/sidekiq/statistic/statistic/metrics/store.rb
Closes https://github.com/davydovanton/sidekiq-statistic/issues/182
Fixes the logging problems with Redis, at least for our environment.
=> Pipelined fixes for redis
