davydovanton/sidekiq-statistic

lib/sidekiq/statistic/base.rb, lib/sidekiq/statistic/statistic/realtime.rb, test/minitest_helper.rb, test/test_sidekiq/statistic_test.rb
This fixes issue #46, where statistics are parsed improperly if a worker class is nested in a module or class, eg. `Nested::HistoryWorker`.
=> Fix statistics display for nested worker classes

lib/sidekiq/statistic/statistic/runtime.rb, lib/sidekiq/statistic/statistic/workers.rb
Hi guys. I've found some problems with 'per day' statistics:
as you see these columns: *time, avg, min, max, last_run* contain incorrect data (just the same data in every row). I've tried to fix it, so you can see now some changes:
The values from the table are the same as data from my redis db. Much better.
=> Fix worker's per day stats

lib/sidekiq/statistic/configuration.rb, lib/sidekiq/statistic/log_parser.rb, lib/sidekiq/statistic/version.rb, test/test_sidekiq/log_parser_test.rb
It is better to parse tail of sidekiq log file because all new jobs are there.
=> Improve configuration and parse last lines of log file

lib/sidekiq/statistic/base.rb
Hi,
This pull request does the following fixes to `to_number()` function:
* correctly process negative numbers
* process integers as integers (they are always processed as floats now) -- I don't know the impact of this point so please let me know if you want to pull only the first commit
Could not run tests but in my setup I see the statistics working fine.
A bit of background so that you understand the intent of the fix better:
Recently we've started to see 500 errors when accessing `/sidekiq/statistic` with no error messages in logs.
After digging through the code I've found that my Redis holds a single broken statistics entry for Sidekiq which caused crashes:
```ruby
["2016-07-20:NotificationWorker:min_time", "-162.529"]
```
Don't know how that value got into the Redis DB.
Anyway I …
=> support negative numbers + fix for converting integers

sidekiq-statistic.gemspec
tilt is required [here](https://github.com/davydovanton/sidekiq-statistic/blob/6f3e4f59b32e5537cb04987b5a69827d349fa8fa/lib/sidekiq/statistic/web_extension.rb#L1)  (`require 'tilt/erb'`) but it's missing from the gemspec. tilt used to be brought in via the sinatra dependency. sidekiq 4.2.0 removed the sinatra dependency so tilt should probably be added to the gemspec.
Without this change users of this gem and sidekiq 4.2 will have to explicitly declare a tilt dependency in their Gemfile.
=> remove sinatra dependency, add tilt dependency

CHANGELOG.md, lib/sidekiq/statistic/configuration.rb, lib/sidekiq/statistic/middleware.rb, test/test_sidekiq/configuration_test.rb, test/test_sidekiq/middleware_test.rb
Trying to address the performance issues noted in https://github.com/davydovanton/sidekiq-statistic/issues/73 and https://github.com/davydovanton/sidekiq-statistic/issues/72.
Thinking about a solution for this, I tried to consider the following:
- Solves the memory issue in a reasonable way without adding complexity.
- Doesn't require a ton of changes to the library.
- Doesn't cause complete flushes of usage stats at random times resulting in invalid timing data when viewing your job stats.
- Doesn't introduce new performance issues.
The solution I came up with here is to simply select a threshold for the number of jobs we want to sample timing data for and once we cross that threshold, safely remove the oldest (_very arbitrary_) 1/4 of the timing values in the list. Note that this **does …
=> Limit the number of entries in timeslist.

.travis.yml, Rakefile, bin/console, lib/sidekiq-statistic.rb, lib/sidekiq/statistic.rb, lib/sidekiq/statistic/base.rb, lib/sidekiq/statistic/configuration.rb, lib/sidekiq/statistic/log_parser.rb, lib/sidekiq/statistic/middleware.rb, lib/sidekiq/statistic/statistic/charts.rb, lib/sidekiq/statistic/statistic/realtime.rb, lib/sidekiq/statistic/statistic/runtime.rb, lib/sidekiq/statistic/statistic/workers.rb, lib/sidekiq/statistic/version.rb, lib/sidekiq/statistic/web_api_extension.rb, lib/sidekiq/statistic/web_extension.rb, lib/sidekiq/statistic/web_extension_helper.rb, test/minitest_helper.rb, test/test_sidekiq/base_statistic_test.rb, test/test_sidekiq/charts_test.rb, test/test_sidekiq/configuration_test.rb, test/test_sidekiq/history.rb, test/test_sidekiq/log_parser_test.rb, test/test_sidekiq/middleware_test.rb, test/test_sidekiq/realtime_test.rb, test/test_sidekiq/runtime_test.rb, test/test_sidekiq/statistic_test.rb, test/test_sidekiq/web_api_extension_test.rb, test/test_sidekiq/web_extension_test.rb
Hi ✋ 
1. This PR adds `frozen_string_literal` comment for all ruby files
2. Drops ruby 2.2, adds 2.5 and updates other ruby versions in Travis
3. Fixes run `./bin/console`
=> Use frozen_string_literal comment

lib/sidekiq/statistic/log_parser.rb
**Before**
```
................../code/sidekiq-statistic/lib/sidekiq/statistic/log_parser.rb:14: warning: File.exists? is a deprecated name, use File.exist? instead
............................../code/sidekiq-statistic/lib/sidekiq/statistic/log_parser.rb:14: warning: File.exists? is a deprecated name, use File.exist? instead
............../code/sidekiq-statistic/lib/sidekiq/statistic/log_parser.rb:14: warning: File.exists? is a deprecated name, use File.exist? instead
........................................................................
Finished in 4.722954s, 14.1860 runs/s, 23.7140 assertions/s.
67 runs, 112 assertions, no failures, no errors, no skips
```
**After**
```
..................................................................................................................... …
```
=> Resolve deprecation warnings

CHANGELOG.md, lib/sidekiq/statistic/middleware.rb, lib/sidekiq/statistic/views/statistic.erb, lib/sidekiq/statistic/views/worker.erb, lib/sidekiq/statistic/web_extension_helper.rb, test/test_sidekiq/base_statistic_test.rb, test/test_sidekiq/runtime_test.rb
1. Changed storing of `last_runtime` in redis from `Date` to `timestamp`
2. Fixed typo from `formate_date` to `format_date`
WAS:
```
{"2019-03-02"=>{"HistoryWorker"=>
{:passed=>1
:last_job_status=>"passed",
:last_time=>"2019-03-02 11:36:02 UTC",
...keys}
```
NOW:
```
{"2015-08-11"=>{"HistoryWorker"=>
{:passed=>1,
:last_job_status=>"failed",
:last_time=>1439335340,
...keys
}
```
@davydovanton 
https://github.com/davydovanton/sidekiq-statistic/issues/87
=> Change storing of last_runtime

README.md
1. Updated README.md guide to create standalone sidekiq server. In newer versions of sidekiq, there is no `middleware` instance variable for `Sidekiq::Web`
https://github.com/davydovanton/sidekiq-statistic/issues/103
=>  Update README.md guide to create standalone Sidekiq server (#103)

CHANGELOG.md, lib/sidekiq/statistic/log_parser.rb, test/helpers/logfile.log, test/test_sidekiq/log_parser_test.rb
1. Changed condition to check if log line contains info about worker.
Was:
Parser was  just checking for substring in log line
Now:
LogParser is now checking for info about worker with updated regex using the `match` method
https://github.com/davydovanton/sidekiq-statistic/issues/123
=> (#123) Change log parser regexp

lib/sidekiq/statistic/views/statistic.erb, lib/sidekiq/statistic/web_extension.rb
The number of busy workers was not being updated in the navbar 
the array name `workers` was conflicting with`workers` inside sidekiq gem `sidekiq/web/views/_summary.erb`
=> fix update busy workers

lib/sidekiq/statistic/locales/pt-br.yml, lib/sidekiq/statistic/views/statistic.erb, lib/sidekiq/statistic/views/worker.erb, lib/sidekiq/statistic/web_extension_helper.rb, test/test_sidekiq/web_extension_helper_test.rb
Related do #132 
To prevent a big translate file with months names, i adopted the following format:
```day/month/year``` ```pt-br.yml``` and ```month/day/year``` as default to prevent errors when the translation is missing.
=> Translate pt-br date format

lib/sidekiq/statistic/log_parser.rb, lib/sidekiq/statistic/views/sidekiq-statistic.css
My sidekiq log usualy has size about 30gb per day and it causes high memory usage
=> fix high memory usage in LogParser

CHANGELOG.md, lib/sidekiq/statistic/helpers/color.rb, lib/sidekiq/statistic/statistic/charts.rb, test/test_sidekiq/helpers/color_test.rb
Related to: https://github.com/davydovanton/sidekiq-statistic/issues/141
- Removes `upcase` in `hex` colors, we don't exactly need to up case letters
- To avoid whites on generated colors I've tried some approaches
- Use base 15 instead of 16 and avoid the `F` letter
- Pros:
- Simple solution
- Would not require too much complexity
- Cons:
- It doesn't solve the same problem for RGB cases
- Excluding `F` letter would lead the hex color to have fewer characters and considering we need to justify the values to build pairs we could end up with the repeated black colors
- Normalize RGB values an use it to generate the HEX one, the logic I used to normalize RGB is basically decreasing the number if it is greater than `215`
- Once the white equivalent in RGB is `255, 255, 255` if we decrease …
=> Refactoring colors helper to avoid light colors

test/test_sidekiq/helpers/date_test.rb, test/test_sidekiq/statistic_test.rb, test/test_sidekiq/web_api_extension_test.rb, test/test_sidekiq/web_extension_test.rb
Minitest 6 will deprecate global expectations, so the most recent versions are already warning us about these.
This PR changes the existing expectations on the project to local (_() syntax).
=> Fix deprecation warnings related to Minitest 6

CHANGELOG.md, lib/sidekiq/statistic/locales/de.yml, lib/sidekiq/statistic/locales/en.yml, lib/sidekiq/statistic/locales/fr.yml, lib/sidekiq/statistic/locales/it.yml, lib/sidekiq/statistic/locales/jp.yml, lib/sidekiq/statistic/locales/pl.yml, lib/sidekiq/statistic/locales/pt-br.yml, lib/sidekiq/statistic/locales/ru.yml, lib/sidekiq/statistic/locales/uk.yml, lib/sidekiq/statistic/views/realtime.erb, lib/sidekiq/statistic/views/realtime_statistic.js, lib/sidekiq/statistic/views/sidekiq-statistic.css
This PR is a feature to #154. 
It changes the old toggle worker visibility checkbox to a button with an icon.
=> Change workers toggle visibility button

lib/sidekiq/statistic/views/realtime_statistic.js
> This PR  fix a problem from #156
Testing I noticed that the workers was being excluded from the chart, BUT not from the server response. Then I realized that it was a mistake in JS code made by me in the last PR that was not adding the hide worker on the list.
@wenderjean I really sorry about that, it was my mistake on the last PR, didn't notice that back there. Now it's working fine :).
----
=> Add excluded workers on real-time request

CHANGELOG.md, lib/sidekiq/statistic/views/sidekiq-statistic.css
Closes #160 
Improved visited anchors in worker table readability in dark mode
Changes are only applied to dark mode, I isolated dark and light mode settings with media queries what will make it easy to change it could be desired in the future
Before: 
After: 
Light mode stills the same:
=> Fix: change workers table visited links color

README.md, lib/sidekiq/statistic.rb, lib/sidekiq/statistic/base.rb, lib/sidekiq/statistic/middleware.rb, lib/sidekiq/statistic/statistic/metric.rb, lib/sidekiq/statistic/statistic/metrics/cache_keys.rb, lib/sidekiq/statistic/statistic/metrics/store.rb, lib/sidekiq/statistic/statistic/realtime.rb, test/minitest_helper.rb, test/statistic/metric_test.rb, test/statistic/metrics/cache_keys_test.rb, test/statistic/metrics/store_test.rb, test/test_sidekiq/base_statistic_test.rb, test/test_sidekiq/middleware_test.rb, test/test_sidekiq/realtime_test.rb
- In order to start attending to new features present in `issues` section I decided to perform some refactorings to clean up the `middleware` module and isolate the responsibility present on it across other specialized modules.
- Share `middleware.rb` responsibilities with new modules `metrics/store`, `statistic/metric.rb` and `metrics/cache_keys`
- Move `REDIS_HASH` to the `metrics/store` module
- Isolate `Time.stub` into a `travel_to` helper method
- Fix minor problems in `README.md`
- Refactor modules that fetch data from Redis in order to isolate them as well
=> Refactoring middleware in order to keep responsibilities isolated

CHANGELOG.md, test/statistic/metrics/cache_keys_test.rb
As far as we use `let` it lazy inits the `metric`. Also, in some tests we have `before` block. It calls metric before the test and do not allow to `Time.stub` block to be called before metric inits. I've removed `before` block to make the test works with `Time.stub` block
@davydovanton looks like previous PR was merged without tests passed :(
=> Fix tests: Remove usage of before block together with Time.stub

.github/workflows/ci.yml, sidekiq-statistic.gemspec
This PR migrates CI to GitHub actions.
To get CI running with `ruby-head` we update the `rake` requirement to `~> 13`
=> Migrate CI to GitHub actions

lib/sidekiq/statistic/statistic/metrics/store.rb
Due to Sidekiq 7 changes on its [Redis gem](https://github.com/mperham/sidekiq/blob/main/docs/7.0-Upgrade.md#redis-client) dependency, the behavior changed a bit. ~~Also, I'm trying to figure out if there is an [actual need to use `pipelined` ](https://github.com/redis-rb/redis-client#pipelining) flow for all those operations.~~
My goal is to maintain compatibility between Sidekiq versions: While Sidekiq 6.x uses `redis` gem, Sidekiq 7.x uses `redis-client` which is more straightforward. Sidekiq 6.x used to return a [Redis::Future](https://msp-greg.github.io/redis/Redis/Future.html) object from pipeline operations, which had to be called with `.value` method to extract the length (return of the function) of it. Now the call for the list length is always returning an Integer.
I've wrapped …
=> Fix Problem with Sidekiq 7
